config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts
  resources :videos
  resources :user_profiles

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root  "studio#index"
  get "/test", to: "studio#test"
  post "/", to: "studio#index"
  get   "introduction", to: "studio#introduction", as: :introduction
  get "user_profiles/:id/public_profile", to: "user_profiles#public_profile", as: :public_profile
  get   "admin/users", to: "admin#show_users", as: :show_users
  get   "admin/videos", to: "admin#show_videos", as: :show_videos
  post "admin/videos/:video_id/publish", to: "admin#publish_video", as: :publish_video
  post "admin/videos/:video_id/unpublish", to: "admin#unpublish_video", as: :unpublish_video
  post "admin/videos/:video_id/assign", to: "admin#assign_video_showed_on_tv", as: :assign_video
  post "admin/videos/:video_id/unassign", to: "admin#unassign_video_showed_on_tv", as: :unassign_video
  get   "contact_us", to: "studio#contact_us", as: :contact_us
  post  "videos/vote/:id", to: "videos#vote_video", as: :vote_video
  post  "videos/unvote/:id", to: "videos#unvote_video", as: :unvote_video

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/admin/_current_admin.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
  <%= image_tag current_user.avatar.url, class: 'profile-image img-circle avatar-img'%>
  <span id="current_admin" ><%= current_user.name %></span>
  <span class = 'caret'></span>
</a>
<ul class="dropdown-menu" role="menu">
  <li><span class="menu-drop-item"><i class="fa fa-user"></i><%= link_to ' Profile', user_profile_path(current_user) %></span></li>
  <% unless(current_user.from_omniauth?) %>
    <li><span class="menu-drop-item"><i class="fa fa-wrench"></i><%= link_to ' Change password', edit_user_registration_path %></span></li>
  <% end %>
  <li><span class="menu-drop-item"><i class="fa fa-tags"></i><%= link_to ' Categories', categories_path %></span></li>
  <li><span class="menu-drop-item"><i class="fa fa-newspaper-o"></i><%= link_to ' Posts', posts_path %></span></li>
  <li><span class="menu-drop-item"><i class="fa fa-video-camera"></i><%= link_to ' Videos', show_videos_path %></span></li>
  <li><span class="menu-drop-item"><i class="fa fa-users"></i><%= link_to ' Users',show_users_path %></span></li>
  <li><span class="menu-drop-item"><i class="fa fa-sign-out"></i><%= link_to ' Logout', destroy_user_session_path, :method => :delete %></span></li>
</ul>

app/views/admin/_users.html.erb
<% @users.each_with_index do |user, index| %>
  <tr>
    <td>
      <%= image_tag user.avatar.url, class: "profile-image img-circle avatar-img" %>
    </td>
    <td> <%= user.email %>
      <% if user.is_admin? %>
        <span class="label label-success" style="float:right;">admin</span>
      <% else %>
      <span class="label label-primary" style="float:right;">user</span>
      <% end %>
    </td>
    <td> <%= user.name %> </td>
    <td> <%= user.birthdate %> </td>
    <td> <%= link_to "Details", public_profile_path(user) %> </td>
  </tr>
<% end %>

app/views/admin/_video_actions.html.erb
<%= link_to "Details", video, class: "btn btn-default" %>
<span>
  <% if video.is_published? %>
    <%= link_to "Unpublish", unpublish_video_path(video), method: :post, remote: true, class: "btn btn-default" %>
  <% else %>
    <%= link_to "Publish", publish_video_path(video), method: :post, remote: true, class: "btn btn-default" %>
  <% end %>
</span>
<% if video.is_showed_on_tv? %>
  <%= link_to "Unassign", unassign_video_path(video), method: :post, remote: true, class: "btn btn-default" %>
<% else %>
  <%= link_to "Assign", assign_video_path(video), class: "btn btn-default" %>
  <% if false %>
    <%= form_tag assign_video_path(video), method: :post, remote: true, id: "assign_form_#{video.id}" do %>
      <%= submit_tag "Assign" %>
      <script>
        $(function(){
          $("#video_<%= video.id %>_showed_date").datepicker({
            format: "dd/mm/yyyy",
            startDate: "01/01/2015",
            endDate: "<%= Date.today %>",
            defaultViewDate: {year: "<%= Date.today.year %>", month: "<%= Date.today.month %>", day: "<%= Date.today.day %>"}
          });
        })
      </script>
      <input type="text" id="video_<%= video.id %>_showed_date" name="showed_date" value="" placeholder="dd/mm/yyyy" class="form-control" style="border: 0;">
    <% end %>
  <% end %>
<% end %>

app/views/admin/_video_status.html.erb
<span class="label label-primary"><%= video.is_published ? "published" : "no published" %></span>
<br>
<span class="label label-success"><%= video.is_showed_on_tv ? "showed" : "no showed" %></span>

app/views/admin/_videos.html.erb
<% @videos.each_with_index do |video, index| %>
  <tr>
    <td>
      <%= video.created_at.strftime("%I:%M:%p") %>
      <br>
      <%= video.created_at.strftime("%d/%m/%Y") %>
    </td>
    <td> <%= video.title %> </td>
    <td id="video_<%= video.id%>_status">
      <%= render partial: 'admin/video_status', locals: {video: video} %>
    </td>
    <td id="video_<%= video.id %>_actions">
      <%= render partial: 'admin/video_actions', locals: {video: video} %>
    </td>
  </tr>
<% end %>

app/views/admin/assign_video_showed_on_tv.html.erb
adkja

app/views/admin/show_users.html.erb
<h1>Listing Users</h1>
<table class="table table-bordered table-condensed table-striped table-hover">
  <tr>
    <th>#</th>
    <th>Email</th>
    <th>Name</th>
    <th>Birthdate</th>
    <th></th>
  </tr>
  <tbody id="admin_users">
    <%= render 'admin/users' %>
  </tbody>
</table>

app/views/admin/show_videos.html.erb
<h1>Listing Videos</h1>
<table class="table table-bordered table-condensed table-striped table-hover">
  <tr>
    <th>Upload date</th>
    <th>Video title</th>
    <th>Status</th>
    <th></th>
  </tr>
  <tbody id="admin_videos">
    <%= render 'admin/videos' %>
  </tbody>
</table>

app/views/admin/video_status.js.erb
$("#video_<%= @video.id %>_status").html("<%=j render partial: 'admin/video_status', locals: {video: @video} %>");
$("#video_<%= @video.id %>_actions").html("<%=j render partial: 'admin/video_actions', locals: {video: @video} %>");