config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts
  resources :videos
  resources :user_profiles

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root  "studio#index"
  get "/test", to: "studio#test"
  post "/", to: "studio#index"
  get   "introduction", to: "studio#introduction", as: :introduction
  get "user_profiles/:id/public_profile", to: "user_profiles#public_profile", as: :public_profile
  get   "admin/users", to: "admin#show_users", as: :show_users
  get   "admin/videos", to: "admin#show_videos", as: :show_videos
  post "admin/videos/:video_id/publish", to: "admin#publish_video", as: :publish_video
  post "admin/videos/:video_id/unpublish", to: "admin#unpublish_video", as: :unpublish_video
  post "admin/videos/:video_id/assign", to: "admin#assign_video_showed_on_tv", as: :assign_video
  post "admin/videos/:video_id/unassign", to: "admin#unassign_video_showed_on_tv", as: :unassign_video
  get   "contact_us", to: "studio#contact_us", as: :contact_us
  post  "videos/vote/:id", to: "videos#vote_video", as: :vote_video
  post  "videos/unvote/:id", to: "videos#unvote_video", as: :unvote_video

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/video.rb
class Video < ActiveRecord::Base
  # include ElasticSearch::Model
  # include ElasticSearch::Model::Callbacks
  include Rails.application.routes.url_helpers

  belongs_to :user
  has_many :video_votes_of_users
  has_many :user_votes, through: :video_votes_of_users, source: :user
  mount_uploader :video, VideoUploader
  validates :title, presence: true, uniqueness: true
  def is_published?
    is_published
  end
  def is_showed_on_tv?
    is_showed_on_tv
  end
  def is_published_in_week(week)
  end
  def is_showed_on_tv_in_week(week)
  end
  def self.search(keyword)
    Video.where("title ~* ?", ".*#{keyword}.*")
  end
  def to_jq_upload
    {
      "name" => title,
      "size" => video.size,
      "url" => video.url,
      "delete_url" => video_path(video),
      "delete_type" => "DELETE"
    }
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy, :vote_video, :unvote_video]
  skip_before_action :authenticate_user!, only: [:show]
  before_action :authorize_user_videos!, only: [:edit, :update, :destroy]
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.where(user_id: current_user.id)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.update(user_id: current_user.id)
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully uploaded.' }
        format.json {
          render json: { files: [@video.to_jq_upload], url: video_path(@video), message: "Uploaded successfully." }, status: :created, location: @video
        }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json {
         render json: { files: [@video.to_jq_upload], url: video_path(@video), message: "Uploaded successfully." }, status: :created, location: @video
        }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def vote_video
    @video_vote = VideoVotesOfUser.new(video_id: params[:id], user_id: current_user.id)
    @video_vote.save
  end
  def unvote_video
    @video_vote = VideoVotesOfUser.where({video_id: params[:id], user_id: current_user.id})
    @video_vote.destroy_all
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:video, :title, :subtitle, :description, :is_published, :is_showed_on_tv, :showed_date)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video, html: { id: "fileupload", format: :json }) do |f| %>
  <% if false && @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>
      <ul>
        <% @video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <% unless @video.new_record? %>
    <%= link_to @video do %>
      <%= image_tag "/img/default_thumbnail.png", style:"width: 196px; height: 110px;", id: "video_#{@video.id}" %>
      Updated at: <i><%= @video.updated_at %></i>
    <% end %>
  <% end %>
  <div class="field" style="margin-top: 10px;">
    <%= render partial: 'videos/upload_video', locals: {f: f} %>
  </div>
<% end %>

app/views/videos/_upload_video.html.erb
<div class="row fileupload-buttonbar" style="margin-left:0px;">
  <div class="row fileupload-buttonbar">
    <div class="col-lg-7">
      <!-- The fileinput-button span is used to style the file input field as button -->
      <span class="btn btn-success fileinput-button">
        <i class="fa fa-file-video-o"></i>
        <span>Choose a video...</span>
        <%= f.file_field :video %>
      </span>
      <span class="fileupload-process"></span>
    </div>
    <!-- The global progress state -->
    <div class="col-lg-5 fileupload-progress fade">
      <!-- The global progress bar -->
      <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
      </div>
      <!-- The extended global progress state -->
      <div class="progress-extended">&nbsp;</div>
    </div>
  </div>
  <!-- The table listing the files available for upload/download -->
  <table role="presentation" class="table table-striped">
    <tbody class="files"></tbody>
  </table>
  <button type="submit" class="btn btn-primary start">
    <i class="fa fa-upload"></i>
    <span>Upload</span>
  </button>
  <%= link_to :back, class: "btn btn-default" do %>
    <i class="fa fa-times"></i>
    Cancel
  <% end %>
</div>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-upload fade">
          <td>
              <span class="preview"></span>
          </td>
          <td>
              <p class="name">{%=file.name%}</p>
              <p class="size">{%=file.size%}</p>
              <strong class="error text-danger"></strong>
          </td>
          <td style="display:none;">
              <p class="size">Processing...</p>
              <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
          </td>
          <td>
              {% if (!i && !o.options.autoUpload) { %}
                  <button class="btn btn-primary start" style="display:none;" name="start-each" disabled>
                      <span>Start</span>
                  </button>
              {% } %}
              {% if (!i) { %}
                  <button class="btn btn-warning cancel">
                      <span>Cancel</span>
                  </button>
              {% } %}
          </td>
      </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-download fade">
          <td>
              <span class="preview">
                  {% if (file.thumbnailUrl) { %}
                      <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                  {% } %}
              </span>
          </td>
          <td>
              <p class="name">
                  {% if (file.url) { %}
                      <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                  {% } else { %}
                      <span>{%=file.name%}</span>
                  {% } %}
              </p>
              {% if (file.error) { %}
                  <div><span class="label label-danger">Error</span> {%=file.error%}</div>
              {% } %}
          </td>
          <td>
              <span class="size">{%=o.formatFileSize(file.size)%}</span>
          </td>
          <td>
              {% if (file.deleteUrl) { %}
                  <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                      <i class="glyphicon glyphicon-trash"></i>
                      <span>Delete</span>
                  </button>
                  <input type="checkbox" name="delete" value="1" class="toggle">
              {% } else { %}
                  <button class="btn btn-warning cancel">
                      <i class="glyphicon glyphicon-ban-circle"></i>
                      <span>Cancel</span>
                  </button>
              {% } %}
          </td>
      </tr>
  {% } %}
</script>
<%= javascript_include_tag 'fileupload' %>
<% if @video.persisted? %>
  <script>
    $(function() {
      $('button[type=submit]').on('click', function(e){
        if($('tbody.files tr').length > 0)
          $('.cancel').hide();
        else{
          $('form#fileupload').attr('format','html').submit();
        }
      });
      $('#fileupload').fileupload({
          url: '/videos/<%= @video.id %>',
          dataType: 'json',
          done: function(e, data) {
            window.location = data.result.url;
          }
      });
    });
  </script>
<% else %>
  <script>
    $(function() {
      $('table[role=presentation]').on('add-row', function(){
        if($('button.start[name=start-each][disabled]').length > 0){
          $('span.fileinput-button').attr('disabled', 'disabled');
          $('button[type=submit]').attr('disabled', 'disabled');
        }
      });
      $('table[role=presentation').on('cancel-row', function(){
        if($('button.start[name=start-each][disabled]').length == 1){
          $('span.fileinput-button').removeAttr('disabled');
          $('button[type=submit]').removeAttr('disabled');
        }
      })
      $('span.fileinput-button').on('click', function(){
        if($('tbody.files tr').length > 0) {
          return false;
        };
      })
      $('#fileupload').fileupload({
          url: '/videos',
          dataType: 'json',
          done: function(e, data) {
            window.location = data.result.url;
          }
      });
    });
  </script>
<% end %>

app/views/videos/_videos.html.erb
<% @videos.each do |video| %>
  <div style="float: left; margin-left: 40px;">
    <%= link_to video do %>
      <%= image_tag "/img/default_thumbnail.png", style:"width: 196px; height: 110px;", id: "video_#{video.id}" %>
    <% end %>
    <p>
      <%= link_to video do %>
        <b><%= video.title %></b>
      <% end %>
      | by
     <%= link_to public_profile_path(video.user) do %>
        <%= video.user.name %>
      <% end %>
      |
      <i id="video_vote_<%= video.id%>">
        <%= video.votes %></i>
      <i class="fa fa-heart"></i>
    </p>
    <% if video.is_published %>
      <span class="label label-primary"><%= video.is_published ? "published" : "not published" %></span>
    <% end %>
    <% if video.is_showed_on_tv %>
      <span class="label label-success"><%= video.is_showed_on_tv ? "showed at #{video.showed_date}" : "not showed" %></span>
    <% end %>
  </div>
<% end %>

app/views/videos/_videos_published.html.erb
<% @videos.each do |video| %>
  <% if video.is_published? %>
    <div style="float: left; margin-left: 40px;">
      <%= image_tag video.thumbnail_url, style:"width: 196px; height: 110px;", id: "video_#{video.id}" %>
      <p><b><%= video.title %></b> | by <%= video.user.email %> | <i id="video_vote_<%= video.id%>"><%= video.votes %></i> votes </p>
      <p><%= video.is_published ? "published" : "not published" %></p>
      <p><%= video.is_showed_on_tv ? "showed at #{video.showed_date}" : "not showed" %></p>
      <%= link_to 'Details', video, class: "btn btn-default" %>
    </div>
  <% end %>
<% end %>

app/views/videos/_videos_showed.html.erb
<% @videos.each do |video| %>
  <% if video.is_showed_on_tv? %>
    <div style="float: left; margin-left: 40px;">
      <%= image_tag video.thumbnail_url, style:"width: 196px; height: 110px;", id: "video_#{video.id}" %>
      <p><b><%= video.title %></b> | by <%= video.user.email %> | <i id="video_vote_<%= video.id%>"><%= video.votes %></i> votes </p>
      <p><%= video.is_published ? "published" : "not published" %></p>
      <p><%= video.is_showed_on_tv ? "showed at #{video.showed_date}" : "not showed" %></p>
      <%= link_to 'Details', video, class: "btn btn-default" %>
    </div>
  <% end %>
<% end %>

app/views/videos/_vote_section.html.erb
<% if current_user.voted?(@video) %>
  <%= link_to "Unvote", unvote_video_path(@video), method: :post, remote: true, class: "label label-success" %>
<% else %>
  <%= link_to 'Vote', vote_video_path(@video), method: :post, remote: true, class: "label label-warning" %>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

app/views/videos/index.html.erb
<h1>Videos</h1>
<%= link_to 'New Video', new_video_path, class: "btn btn-default" %>
<div style="margin: 10px;">
  
</div>
<%= render 'videos/videos' %>

app/views/videos/new.html.erb
<h1>Upload Video</h1>

<%= render 'form' %>

app/views/videos/show.html.erb
<div class='col-md-offset-3' style="margin-top: 50px;">
  <video id="video_<%= @video.id %>" class="video-js vjs-default-skin"
  controls preload="auto" width="480" height="360"
  data-setup='{}'>
    <source src="<%= @video.video.url%>" type='video/mp4' />
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>
  <p>
    <b><%= @video.title %></b> | by <%= @video.user.name %> | <i id="video_vote_<%= @video.id%>"><%= @video.votes %></i> <i class="fa fa-heart"></i>
    <span id="video_<%= @video.id %>_vote_section">
      <%= render 'videos/vote_section' %>
    </span>
  </p>
  <div style="margin-bottom: 10px;">
    <% if @video.is_published %>
      <span class="label label-primary"><%= @video.is_published ? "published" : "not published" %></span>
    <% end %>
    <% if @video.is_showed_on_tv %>
      <span class="label label-success"><%= @video.is_showed_on_tv ? "showed at #{@video.showed_date}" : "not showed" %></span>
    <% end %>
  </div>
  <div class="actions">
    <% if current_user && current_user.is_owner?(@video) %>
      <%= link_to 'Edit', edit_video_path(@video), class: "btn btn-default" %>
      <%= link_to 'Take it off', video_path(@video), method: :delete, data: { confirm: "Are you sure" }, class: "btn btn-default" %>
    <% end %>
    <%= link_to 'Back', root_path, class: "btn btn-default" %>
  </div>
</div>

app/views/videos/unvote_video.js.erb
$("#video_vote_<%= @video.id %>").html("<%= @video.reload.votes%>")
$("#video_<%= @video.id %>_vote_section").html("<%=j render 'videos/vote_section'%>")

app/views/videos/vote_video.js.erb
$("#video_vote_<%= @video.id %>").html("<%= @video.reload.votes%>")
$("#video_<%= @video.id %>_vote_section").html("<%=j render 'videos/vote_section'%>")