config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts
  resources :videos
  resources :user_profiles

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root  "studio#index"
  get "/test", to: "studio#test"
  post "/", to: "studio#index"
  get   "introduction", to: "studio#introduction", as: :introduction
  get "user_profiles/:id/public_profile", to: "user_profiles#public_profile", as: :public_profile
  get   "admin/users", to: "admin#show_users", as: :show_users
  get   "admin/videos", to: "admin#show_videos", as: :show_videos
  post "admin/videos/:video_id/publish", to: "admin#publish_video", as: :publish_video
  post "admin/videos/:video_id/unpublish", to: "admin#unpublish_video", as: :unpublish_video
  post "admin/videos/:video_id/assign", to: "admin#assign_video_showed_on_tv", as: :assign_video
  post "admin/videos/:video_id/unassign", to: "admin#unassign_video_showed_on_tv", as: :unassign_video
  get   "contact_us", to: "studio#contact_us", as: :contact_us
  post  "videos/vote/:id", to: "videos#vote_video", as: :vote_video
  post  "videos/unvote/:id", to: "videos#unvote_video", as: :unvote_video

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_flash.html.erb
<div id="flash">
<% if notice || alert %>
  <div class="notifyjs-corner">
    <% if notice %>
      <script>
        $.notify("<%=j notice %>", {className: "success"});
      </script>
    <% elsif alert %>
      <script>
        $.notify("<%=j alert %>", {className: "warn"});
      </script>
    <% end %>
  </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">

</div>

app/views/layouts/_header.html.erb
<div id="header">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= @page_title || "East Studio" %></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
        <ul class="nav navbar-nav">
          <li><a href="/"><i class="fa fa-home fa-fw"></i> Home</a></li>
          <li><a href="<%= introduction_path %>"><i class="fa fa-leanpub"></i> Introduction</a></li>
          <li><a href="<%= new_video_path %>"><i class="fa fa-video-camera"></i> Upload new video</a></li>
          <li><a href="<%= posts_path %>"><i class="fa fa-newspaper-o"></i> Posts</a></li>
          <li><a href="<%= contact_us_path %>"><i class="fa fa-at"></i> Contact us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= render("layouts/user_status") %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_user_status.html.erb
  <% if user_signed_in? %>
  <li class="dropdown">
    <% if current_user.is_admin? %>
      <%= render 'admin/current_admin' %>
    <% else %>
      <%= render 'users/current_user' %>
    <% end %>
  </li>
<% else %>
  <li>
    <% if controller_name != 'sessions' %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </li>
  <li><% if controller_name != 'registrations' %>
      <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eaststudio</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <div id="page" class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>